/**
 * Worker entry point.
 *
 * Wraps the OpenNext handler purely to attach security headers to every
 * response. This is done here rather than anywhere more obvious because both
 * of the usual places silently fail on this stack:
 *
 *  - `public/_headers` is a Cloudflare *Pages* feature; Workers ignores it.
 *  - Next's `headers()` never runs for prerendered routes, because OpenNext
 *    serves that HTML straight from the assets binding without invoking the
 *    Next server.
 *
 * Wrapping the fetch handler catches everything: static assets, prerendered
 * HTML, and dynamic routes alike.
 */
// @ts-expect-error - generated by `opennextjs-cloudflare build`
import handler from "./.open-next/worker.js";

const SECURITY_HEADERS: Record<string, string> = {
  "Strict-Transport-Security": "max-age=63072000; includeSubDomains; preload",
  "X-Content-Type-Options": "nosniff",
  "X-Frame-Options": "DENY",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy":
    "camera=(), microphone=(), geolocation=(), interest-cohort=()",
  "Cross-Origin-Opener-Policy": "same-origin",
  "X-DNS-Prefetch-Control": "on",
};

export default {
  async fetch(request: Request, env: unknown, ctx: unknown): Promise<Response> {
    const response = await handler.fetch(request, env, ctx);

    // A 101 (websocket upgrade) response has an immutable, bodiless shape that
    // must be passed through untouched.
    if (response.status === 101) return response;

    const headers = new Headers(response.headers);
    for (const [key, value] of Object.entries(SECURITY_HEADERS)) {
      headers.set(key, value);
    }

    return new Response(response.body, {
      status: response.status,
      statusText: response.statusText,
      headers,
    });
  },
};

// Durable Objects and the cache-purge binding must stay exported from the
// entry point or Wrangler cannot find their class definitions.
export { BucketCachePurge, DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";
